In [17]:
from selenium.webdriver.common.by import By
from selenium import webdriver
from selenium.webdriver.support.ui import Select
from bs4 import BeautifulSoup
import pandas as pd
import time

In [18]:


#find the advanced data of all players from year_a to year_b
def find_advanced(year_a,year_b):

    year_gap = year_b - year_a
    year_to_2022 = 2022 - year_b
    
    for i in range(year_gap+1):
        # open the browser
        driver = webdriver.Firefox()
        url = r"https://www.nba.com/stats/players/advanced/?sort=GP&dir=-1&Season=2021-22&SeasonType=Regular%20Season"
        driver.get(url)
        #select a year
        time.sleep(5)
        select = Select(driver.find_element(By.XPATH,"/html/body/main/div/div/div[2]/div/div/div[1]/div[1]/div/div/label/select"))
        select.select_by_index(i+year_to_2022)
        
        time.sleep(10)
        # select the page number to all
        select = Select(driver.find_element(By.XPATH,"/html/body/main/div/div/div[2]/div/div/nba-stat-table/div[1]/div/div/select"))
        select.select_by_index(0)
        
        #find the table 
        src = driver.page_source
        parser = BeautifulSoup(src,"lxml")
        table = parser.find("div",attrs = {"class" : "nba-stat-table__overflow"})
        
        #find the header of the table and remove the attributes that are not shown
        headers = table.find_all('th')
        headerlist = [h.text.strip() for h in headers[1:]]
        headerlist1 = [a for a in headerlist if not "RANK" in a]
        
        #get the data of from all the data cells
        rows = table.findAll('tr')[1:]
        player_stats = [[td.getText().strip() for td in rows[i].findAll('td')[1:]] for i in range(len(rows))]
        
        #drop the last 5 attributes that are hidden in the table 
        headerlist1 = headerlist1[:-5]
        
        #drop the data into the pdDataFrame
        stats = pd.DataFrame(player_stats,columns=headerlist1)
        
        #add the year infront of the player's name
        def add_year(x):
            return "_"+str(year_b - i)+"_"+x
        stats["PLAYER"] = stats["PLAYER"].map(add_year)
        #save the data as an excel table
        pd.DataFrame.to_excel(stats,"./newdata/advanced"+str(year_b-i)+".xlsx")
        driver.close()
        print("data of "+str(year_b-i)+" has been saved")
    return

In [20]:
find_advanced(2013,2014)

NoSuchWindowException: Message: Browsing context has been discarded
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:188:5
NoSuchWindowError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:614:5
assert.that/<@chrome://remote/content/shared/webdriver/Assert.sys.mjs:485:13
assert.open@chrome://remote/content/shared/webdriver/Assert.sys.mjs:147:4
GeckoDriver.prototype.findElement@chrome://remote/content/marionette/driver.sys.mjs:1496:15
despatch@chrome://remote/content/marionette/server.sys.mjs:318:40
execute@chrome://remote/content/marionette/server.sys.mjs:289:16
onPacket/<@chrome://remote/content/marionette/server.sys.mjs:262:20
onPacket@chrome://remote/content/marionette/server.sys.mjs:263:9
_onJSONObjectReady/<@chrome://remote/content/marionette/transport.sys.mjs:494:20

In [21]:
#find the regular data per game of all players from year_a to year_b
def find_regular_pg(year_a,year_b):

    year_gap = year_b - year_a
    year_to_2022 = 2022 - year_b
    
    for i in range(year_gap+1):
        driver = webdriver.Firefox()
        url = r"https://www.nba.com/stats/players/traditional/?SeasonType=Regular%20Season&sort=PTS&dir=-1&Season=2021-22"
        driver.get(url)
        
        #select a year
        time.sleep(5)
        select = Select(driver.find_element(By.XPATH,"/html/body/main/div/div/div[2]/div/div/div[1]/div[1]/div/div/label/select"))
        select.select_by_index(i+year_to_2022)
        
        time.sleep(10)
        # select the page number to all
        select = Select(driver.find_element(By.XPATH,"/html/body/main/div/div/div[2]/div/div/nba-stat-table/div[1]/div/div/select"))
        select.select_by_index(0)
        
        #find the table 
        src = driver.page_source
        parser = BeautifulSoup(src,"lxml")
        table = parser.find("div",attrs = {"class" : "nba-stat-table__overflow"})
        
        #find the header of the table and remove the attributes that are not shown
        headers = table.find_all('th')
        headerlist = [h.text.strip() for h in headers[1:]]
        headerlist1 = [a for a in headerlist if not "RANK" in a]
        
        #get the data of from all the data cells
        rows = table.findAll('tr')[1:]
        player_stats = [[td.getText().strip() for td in rows[i].findAll('td')[1:]] for i in range(len(rows))]
        
        #drop the data into the pdDataFrame
        stats = pd.DataFrame(player_stats,columns=headerlist1)
        
        #add the year infront of the player's name
        def add_year(x):
            return "_"+str(year_b - i)+"_"+x
        stats["PLAYER"] = stats["PLAYER"].map(add_year)
        #save the data as an excel table
        pd.DataFrame.to_excel(stats,"./newdata/per_game_regular"+str(year_b-i)+".xlsx")
        driver.close()
        print("data of "+str(year_b-i)+" has been saved")
    return

In [ ]:
find_regular_pg(2000,2022)

NoSuchElementException: Message: Unable to locate element: /html/body/main/div/div/div[2]/div/div/div[1]/div[1]/div/div/label/select; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:188:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:506:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:132:16

In [22]:
find_regular_pg(2015,2022)

NoSuchWindowException: Message: Browsing context has been discarded
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:188:5
NoSuchWindowError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:614:5
assert.that/<@chrome://remote/content/shared/webdriver/Assert.sys.mjs:485:13
assert.open@chrome://remote/content/shared/webdriver/Assert.sys.mjs:147:4
GeckoDriver.prototype.findElement@chrome://remote/content/marionette/driver.sys.mjs:1496:15
despatch@chrome://remote/content/marionette/server.sys.mjs:318:40
execute@chrome://remote/content/marionette/server.sys.mjs:289:16
onPacket/<@chrome://remote/content/marionette/server.sys.mjs:262:20
onPacket@chrome://remote/content/marionette/server.sys.mjs:263:9
_onJSONObjectReady/<@chrome://remote/content/marionette/transport.sys.mjs:494:20

In [ ]:
find_regular_pg(2000,2015)

data of 2015 has been saved
data of 2014 has been saved
data of 2013 has been saved
data of 2012 has been saved
data of 2011 has been saved
data of 2010 has been saved
data of 2009 has been saved
data of 2008 has been saved
data of 2007 has been saved
data of 2006 has been saved
data of 2005 has been saved
data of 2004 has been saved
data of 2003 has been saved
data of 2002 has been saved
data of 2001 has been saved
data of 2000 has been saved

In [ ]:
#find the regular data per game of all players from year_a to year_b
def find_regular_p100(year_a,year_b):

    year_gap = year_b - year_a
    year_to_2022 = 2022 - year_b
    
    for i in range(year_gap+1):
        driver = webdriver.Firefox()
        url = "https://www.nba.com/stats/players/traditional/?sort=PTS&dir=-1&Season=2021-22&SeasonType=Regular%20Season"
        driver.get(url)
        
        #choose year
        time.sleep(10)
        select = Select(driver.find_element(By.XPATH,"/html/body/main/div/div/div[2]/div/div/div[1]/div[1]/div/div/label/select"))
        select.select_by_index(i+year_to_2022)
        
        #choose per 100 poss
        time.sleep(10)
        select = Select(driver.find_element(By.XPATH,"/html/body/main/div/div/div[2]/div/div/div[1]/div[3]/div/div/label/select"))
        select.select_by_index(2)
        
        time.sleep(10)
        # select the page number to all
        select = Select(driver.find_element(By.XPATH,"/html/body/main/div/div/div[2]/div/div/nba-stat-table/div[1]/div/div/select"))
        select.select_by_index(0)
        
        #find the table 
        src = driver.page_source
        parser = BeautifulSoup(src,"lxml")
        table = parser.find("div",attrs = {"class" : "nba-stat-table__overflow"})
        
        #find the header of the table and remove the attributes that are not shown
        headers = table.find_all('th')
        headerlist = [h.text.strip() for h in headers[1:]]
        headerlist1 = [a for a in headerlist if not "RANK" in a]
        
        #get the data of from all the data cells
        rows = table.findAll('tr')[1:]
        player_stats = [[td.getText().strip() for td in rows[i].findAll('td')[1:]] for i in range(len(rows))]
        
        #drop the data into the pdDataFrame
        stats = pd.DataFrame(player_stats,columns=headerlist1)
        
        #add the year infront of the player's name
        def add_year(x):
            return "_"+str(year_b - i)+"_"+x
        stats["PLAYER"] = stats["PLAYER"].map(add_year)
        #save the data as an excel table
        pd.DataFrame.to_excel(stats,"./newdata/per_100_regular"+str(year_b-i)+".xlsx")
        driver.close()
        print("data of "+str(year_b-i)+" has been saved")
    return

In [ ]:
find_regular_p100(2012,2022)

NoSuchElementException: Message: Unable to locate element: /html/body/main/div/div/div[2]/div/div/div[1]/div[1]/div/div/label/select; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:188:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:506:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:132:16

In [ ]:
find_regular_p100(2010,2022)

NoSuchElementException: Message: Unable to locate element: /html/body/main/div/div/div[2]/div/div/div[1]/div[1]/div/div/label/select; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:188:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:506:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:132:16

In [23]:
def find_regular_total(year_a,year_b):

    year_gap = year_b - year_a
    year_to_2022 = 2022 - year_b
    
    for i in range(year_gap+1):
        driver = webdriver.Firefox()
        url = "https://www.nba.com/stats/players/traditional/?SeasonType=Regular%20Season&sort=PTS&dir=-1&Season=2021-22&PerMode=Totals"
        driver.get(url)
        
        #choose year
        time.sleep(10)
        select = Select(driver.find_element(By.XPATH,"/html/body/main/div/div/div[2]/div/div/div[1]/div[1]/div/div/label/select"))
        select.select_by_index(i+year_to_2022)
        
        time.sleep(10)
        # select the page number to all
        select = Select(driver.find_element(By.XPATH,"/html/body/main/div/div/div[2]/div/div/nba-stat-table/div[1]/div/div/select"))
        select.select_by_index(0)
        
        #find the table 
        src = driver.page_source
        parser = BeautifulSoup(src,"lxml")
        table = parser.find("div",attrs = {"class" : "nba-stat-table__overflow"})
        
        #find the header of the table and remove the attributes that are not shown
        headers = table.find_all('th')
        headerlist = [h.text.strip() for h in headers[1:]]
        headerlist1 = [a for a in headerlist if not "RANK" in a]
        
        #get the data of from all the data cells
        rows = table.findAll('tr')[1:]
        player_stats = [[td.getText().strip() for td in rows[i].findAll('td')[1:]] for i in range(len(rows))]
        
        #drop the data into the pdDataFrame
        stats = pd.DataFrame(player_stats,columns=headerlist1)
        
        #add the year infront of the player's name
        def add_year(x):
            return "_"+str(year_b - i)+"_"+x
        stats["PLAYER"] = stats["PLAYER"].map(add_year)
        stats["TEAM"] = stats["TEAM"].map(add_year)
        #save the data as an excel table
        pd.DataFrame.to_excel(stats,"./project_data/regular_total_data/"+"regular_total"+str(year_b-i)+".xlsx")
        driver.close()
        print("data of "+str(year_b-i)+" has been saved")
    return

In [ ]:
find_regular_total(2010,2022)

NoSuchWindowException: Message: Browsing context has been discarded
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:188:5
NoSuchWindowError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:614:5
assert.that/<@chrome://remote/content/shared/webdriver/Assert.sys.mjs:485:13
assert.open@chrome://remote/content/shared/webdriver/Assert.sys.mjs:147:4
GeckoDriver.prototype.findElement@chrome://remote/content/marionette/driver.sys.mjs:1496:15
despatch@chrome://remote/content/marionette/server.sys.mjs:318:40
execute@chrome://remote/content/marionette/server.sys.mjs:289:16
onPacket/<@chrome://remote/content/marionette/server.sys.mjs:262:20
onPacket@chrome://remote/content/marionette/server.sys.mjs:263:9
_onJSONObjectReady/<@chrome://remote/content/marionette/transport.sys.mjs:494:20

In [ ]:
find_regular_total(2000,2009)

data of 2009 has been saved
data of 2008 has been saved
data of 2007 has been saved
data of 2006 has been saved
data of 2005 has been saved
data of 2004 has been saved
data of 2003 has been saved
data of 2002 has been saved
data of 2001 has been saved
data of 2000 has been saved

In [24]:
#find the defense data of all players from year_a to year_b
def find_defense(year_a,year_b):

    year_gap = year_b - year_a
    year_to_2022 = 2022 - year_b
    
    for i in range(year_gap+1):
        # open the browser
        driver = webdriver.Firefox()
        url = r"https://www.nba.com/stats/players/usage/?sort=USG_PCT&dir=-1&Season=2021-22&SeasonType=Regular%20Season"
        driver.get(url)
        #select a year
        time.sleep(15)
        select = Select(driver.find_element(By.XPATH,"/html/body/main/div/div/div[2]/div/div/div[1]/div[1]/div/div/label/select"))
        select.select_by_index(i+year_to_2022)
        
        time.sleep(10)
        # select the page number to all
        select = Select(driver.find_element(By.XPATH,"/html/body/main/div/div/div[2]/div/div/nba-stat-table/div[1]/div/div/select"))
        select.select_by_index(0)
        
        #find the table 
        src = driver.page_source
        parser = BeautifulSoup(src,"lxml")
        table = parser.find("div",attrs = {"class" : "nba-stat-table__overflow"})
        
        #find the header of the table and remove the attributes that are not shown
        headers = table.find_all('th')
        headerlist = [h.text.strip() for h in headers[1:]]
        headerlist1 = [a for a in headerlist if not "RANK" in a]
        
        #get the data of from all the data cells
        rows = table.findAll('tr')[1:]
        player_stats = [[td.getText().strip() for td in rows[i].findAll('td')[1:]] for i in range(len(rows))]
        
        #drop the data into the pdDataFrame
        stats = pd.DataFrame(player_stats,columns=headerlist1)
        
        #add the year infront of the player's name
        def add_year(x):
            return "_"+str(year_b - i)+"_"+x
        stats["Player"] = stats["Player"].map(add_year)
        #save the data as an excel table
        pd.DataFrame.to_excel(stats,"./project_data/defense_data/defense"+str(year_b-i)+".xlsx")
        driver.close()
        print("data of "+str(year_b-i)+" has been saved")
    return

In [ ]:
find_defense(2015,2022)

data of 2022 has been saved
data of 2021 has been saved
data of 2020 has been saved
data of 2019 has been saved
data of 2018 has been saved
data of 2017 has been saved
data of 2016 has been saved
data of 2015 has been saved

In [ ]:
find_defense(2000,2013)

data of 2013 has been saved
data of 2012 has been saved
data of 2011 has been saved
data of 2010 has been saved
data of 2009 has been saved
data of 2008 has been saved
data of 2007 has been saved
data of 2006 has been saved
data of 2005 has been saved
data of 2004 has been saved
data of 2003 has been saved
data of 2002 has been saved
data of 2001 has been saved
data of 2000 has been saved

In [ ]:
#find the opponent data of all players from year_a to year_b
def find_usage(year_a,year_b):

    year_gap = year_b - year_a
    year_to_2022 = 2022 - year_b
    
    for i in range(year_gap+1):
        # open the browser
        driver = webdriver.Firefox()
        url = r"https://www.nba.com/stats/players/usage/?sort=USG_PCT&dir=-1&Season=2021-22&SeasonType=Regular%20Season"
        driver.get(url)
        #select a year
        time.sleep(15)
        select = Select(driver.find_element(By.XPATH,"/html/body/main/div/div/div[2]/div/div/div[1]/div[1]/div/div/label/select"))
        select.select_by_index(i+year_to_2022)
        
        time.sleep(10)
        # select the page number to all
        select = Select(driver.find_element(By.XPATH,"/html/body/main/div/div/div[2]/div/div/nba-stat-table/div[1]/div/div/select"))
        select.select_by_index(0)
        
        #find the table 
        src = driver.page_source
        parser = BeautifulSoup(src,"lxml")
        table = parser.find("div",attrs = {"class" : "nba-stat-table__overflow"})

        #find the header of the table and remove the attributes that are not shown
        headers = table.find_all('th')
        headerlist = [h.text.strip() for h in headers[1:]]
        headerlist1 = [a for a in headerlist if not "RANK" in a]
        
        #get the data of from all the data cells
        rows = table.findAll('tr')[1:]
        player_stats = [[td.getText().strip() for td in rows[i].findAll('td')[1:]] for i in range(len(rows))]
        stats = pd.DataFrame(player_stats,columns=headerlist1)

        #drop the data into the pdDataFrame
        stats = pd.DataFrame(player_stats,columns=headerlist1)
        
        #add the year infront of the player's name
        def add_year(x):
            return "_"+str(year_b - i)+"_"+x
        stats["Player"] = stats["Player"].map(add_year)
        #save the data as an excel table
        pd.DataFrame.to_excel(stats,"./project_data/usage_data/usage"+str(year_b-i)+".xlsx")
        driver.close()
        print("data of "+str(year_b-i)+" has been saved")
    return

In [ ]:
find_usage(2015,2022)

data of 2022 has been saved
data of 2021 has been saved
data of 2020 has been saved
data of 2019 has been saved
data of 2018 has been saved
data of 2017 has been saved
data of 2016 has been saved
data of 2015 has been saved

In [ ]:
find_usage(2000,2014)

data of 2014 has been saved
data of 2013 has been saved
data of 2012 has been saved
data of 2011 has been saved
data of 2010 has been saved
data of 2009 has been saved
data of 2008 has been saved
data of 2007 has been saved
data of 2006 has been saved
data of 2005 has been saved
data of 2004 has been saved
data of 2003 has been saved
data of 2002 has been saved
data of 2001 has been saved
data of 2000 has been saved

In [ ]:
### find the game log of each team and player

In [26]:
driver = webdriver.Firefox()
url = "https://www.nba.com/stats/teams/boxscores?Season=2021-22"
driver.get(url)

In [ ]:
select = Select(driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[3]/section[2]/div/div[2]/div[2]/div[1]/div[3]/div/label/div/select"))
src = driver.page_source
parser = BeautifulSoup(src,"lxml")
table = parser.find("div",attrs = {"class" : "Crom_container__C45Ti"})

In [ ]:
headers = table.find_all('th')
headerlist = [h.text.strip() for h in headers]
rows = table.findAll('tr')[1:]
team_stats = [[td.getText().strip() for td in rows[i].findAll('td')] for i in range(len(rows))]

In [ ]:
team_stats = pd.DataFrame(team_stats,columns=headerlist)

In [ ]:
team_stats.to_excel("./project_data/team_box_score.xlsx")

In [ ]:
driver.close()

In [ ]:
driver = webdriver.Firefox()
url = "https://www.nba.com/stats/players/boxscores?Season=2021-22"
driver.get(url)

In [ ]:
select = Select(driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[2]/div[3]/section[2]/div/div[2]/div[2]/div[1]/div[3]/div/label/div/select"))
select.select_by_index(0)

In [ ]:
src = driver.page_source
parser = BeautifulSoup(src,"lxml")
table = parser.find("div",attrs = {"class" : "Crom_container__C45Ti"})

In [ ]:
headers = table.find_all('th')
headerlist = [h.text.strip() for h in headers]

In [ ]:
rows = table.findAll('tr')[1:]
players_stats = [[td.getText().strip() for td in rows[i].findAll('td')] for i in range(len(rows))]

In [ ]:
players_stats = pd.DataFrame(players_stats,columns=headerlist)

In [ ]:
players_stats.to_excel("./project_data/player_box_score.xlsx")

In [ ]:
players_stats

,PLAYER,TEAM,MATCH UP,GAME DATE,W/L,MIN,PTS,FGM,FGA,FG%,...,OREB,DREB,REB,AST,STL,BLK,TOV,PF,+/-,FP
0,Malcolm Hill,CHI,CHI @ MIN,04/10/2022,W,13,2,1,2,50.0,...,0,3,3,3,1,0,1,2,-9,12.1
1,Ayo Dosunmu,CHI,CHI @ MIN,04/10/2022,W,45,26,9,18,50.0,...,2,3,5,6,2,0,7,2,10,40.0
2,Nathan Knight,MIN,MIN vs. CHI,04/10/2022,L,16,17,7,12,58.3,...,2,6,8,3,0,0,1,4,16,30.1
3,Leandro Bolmaro,MIN,MIN vs. CHI,04/10/2022,L,18,11,4,9,44.4,...,1,2,3,4,0,0,0,1,15,20.6
4,Patrick Williams,CHI,CHI @ MIN,04/10/2022,W,41,35,10,21,47.6,...,0,4,4,4,0,1,5,2,-8,43.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26034,Nemanja Bjelica,GSW,GSW @ LAL,10/19/2021,W,26,15,6,7,85.7,...,2,9,11,4,1,0,1,2,20,36.2
26035,Malik Monk,LAL,LAL vs. GSW,10/19/2021,L,19,6,2,5,40.0,...,0,3,3,1,2,0,1,1,-10,16.1
26036,Dwight Howard,LAL,LAL vs. GSW,10/19/2021,L,13,5,1,2,50.0,...,0,6,6,0,0,0,2,2,-7,10.2
26037,LeBron James,LAL,LAL vs. GSW,10/19/2021,L,37,34,13,23,56.5,...,1,10,11,5,1,1,4,5,-2,56.7
26038,Avery Bradley,LAL,LAL vs. GSW,10/19/2021,L,8,6,2,3,66.7,...,1,0,1,1,0,0,1,2,1,7.7

In [ ]:
len(team_stats)

2460

In [ ]:
team_stats

,Team,Match Up,Game Date,W/L,MIN,PTS,FGM,FGA,FG%,3PM,...,FT%,OREB,DREB,REB,AST,STL,BLK,TOV,PF,+/-
0,CHI,CHI @ MIN,04/10/2022,W,240,124,44,83,53.0,10,...,78.8,16,32,48,22,9,3,23,22,4
1,MIN,MIN vs. CHI,04/10/2022,L,240,120,46,91,50.5,11,...,77.3,9,23,32,30,7,9,13,23,-4
2,PHI,PHI vs. DET,04/10/2022,W,240,118,46,88,52.3,5,...,91.3,10,32,42,25,13,6,11,23,12
3,DET,DET @ PHI,04/10/2022,L,240,106,38,83,45.8,11,...,65.5,15,27,42,26,4,4,20,16,-12
4,BOS,BOS @ MEM,04/10/2022,W,240,139,54,99,54.5,18,...,100,14,42,56,34,5,2,15,20,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,IND,IND @ CHA,10/20/2021,L,240,122,42,90,46.7,17,...,87.5,8,43,51,29,2,10,17,24,-1
2456,BKN,BKN @ MIL,10/19/2021,L,240,104,37,84,44.0,17,...,56.5,5,39,44,19,3,9,13,17,-23
2457,MIL,MIL vs. BKN,10/19/2021,W,240,127,48,105,45.7,17,...,77.8,13,41,54,25,8,9,8,19,23
2458,GSW,GSW @ LAL,10/19/2021,W,240,121,41,93,44.1,14,...,83.3,9,41,50,30,9,2,17,18,7
2459,LAL,LAL vs. GSW,10/19/2021,L,240,114,45,95,47.4,15,...,47.4,5,40,45,21,7,4,18,25,-7

In [ ]:
team_stats = pd.read_excel("./project_data/team_box_score.xlsx")

In [ ]:
team_stats_arr = team_stats.to_numpy()
team_stats_arr[0,7]

83

In [ ]:
import numpy as np

In [ ]:
team_difference = np.empty([1230, 19])

In [25]:
for i in range(1230):
    if team_stats_arr[2*i,3] == "W":
        team_difference[i,-1] = 1
        for j in range(18):
            team_difference[i,j] = team_stats_arr[2*i,j+5] - team_stats_arr[2*i+1,j+5]
    if team_stats_arr[2*i,3] == "L":
        team_difference[i,-1] = 0
        for j in range(18):
            team_difference[i,j] = team_stats_arr[2*i+1,j+5] - team_stats_arr[2*i,j+5]

NameError: name 'team_stats_arr' is not defined

In [ ]:
team_difference

array([[ 4., -2., -8., ..., 10., -1.,  1.],
       [12.,  8.,  5., ..., -9.,  7.,  1.],
       [29., 15., -3., ...,  5.,  4.,  1.],
       ...,
       [ 1.,  4., 17., ..., -9., -3.,  1.],
       [23., 11., 21., ..., -5.,  2.,  0.],
       [ 7., -4., -2., ..., -1., -7.,  1.]])

In [ ]:
column = ['PTS',
 'FGM',
 'FGA',
 'FG%',
 '3PM',
 '3PA',
 '3P%',
 'FTM',
 'FTA',
 'FT%',
 'OREB',
 'DREB',
 'REB',
 'AST',
 'STL',
 'BLK',
 'TOV',
 'PF',
 'result']

In [ ]:
team_difference_df = pd.DataFrame(team_difference, columns = column)

In [ ]:
team_difference_df.to_excel("./project_data/team_difference.xlsx")